### ISSUE TITLE
ToDo List Basics

### ISSUE THREAD

**Issue by OskarWiedeweg** [OskarWiedeweg/res-TodoApp#1]
**Base Idea**
The `ToDo List` is a simple list, containing items like text (or other types that might be added in the future). 
Each todo list refers to one user, but could be made accessible to other users as well.

**Road Map**
- [x] ToDo list entity
- [x] ToDo list is refers to one user
- [x] Items can be added to the ToDo List
- [x] Items can be removed, edited or marked as done
